FROM python:3.9

WORKDIR /app

COPY ./main.py ./main.py
COPY ./server ./server
COPY ./examples ./examples

RUN pip install --no-cache-dir flask

CMD ["python", "main.py", "--test-run", "/app/examples/basic-test-run.json"]
